markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Core Ruby
url: http://hachbulgaria.com/ruby
description: The Hack Bulgaria class about all the nitty gritty details in Ruby
twitter: hackbulgaria
